phoenix-rtos/libphoenix

Makefile
Use mkdir -p instead install -D, because "-D" option does not exist on all platforms
=> makefile: platform independent install dir creation

string/string.c
strtok delimiters can change between calls for the same str so you can't call strspn in advance
=> string: strtok fix for alternating delimiters

arch/arm-imx/string.c, arch/armv7/string.c, string/string.c
strncpy should pad dest string with zeroes when src len is less that n
=> strncpy fix

unistd/dir.c
dirname and basename didn't handle properly NULL input and "", "/a/", "a/", "a///b" cases
=> unistd: posix compatible dirname and basename

.gitignore, Makefile, include/pthread.h, include/sched.h, include/sys/types.h, pthread/pthread.c, test/Makefile, test/test_pthreads.c
Initial implementation contains basic pthread operations (create, join, detach) as well as pthread attributes setting and basic mutexes. Not all operation modes are supported yet. The test_pthreads.c contains tests for implemented functionalities.
=> pthread: add initial impl of posix threads

Makefile
LIBNAME is essential in creating symlinks to libphoenix.a in toolchain's libs.
=> Makefile: restore missing LIBNAME value

include/endian.h
This change is required by pc-ata (it uses endian conversions).
=> endian.h: use uintX_t insted of uX

include/dirent.h
This change is necessary for my new implementation of ls utility.
=> dirent.h: Add dtSymlink dirent type

stdlib/malloc_dl.c
_malloc_chunkSplit() caused load page fault exception on RISC-V by assuming that 'size' parameter is greater than CHUNK_OVERHEAD (for RISC-V64 it's 16 bytes instead of 8 bytes on a 32-bit architecture).
=> malloc_dl: malloc_chunkCanSplit() quick fix for RISC-V

arch/arm/string.c
Since copying is done from the end, the addresses `src+l` and `dst+l` should be aligned, not `src` and `dst`.
=> arm/string.c: memmove improved copying from the end

include/sys/mman.h
PR with changes on kernel side: [link](https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/170)
=> sys/mman.h: moved predefined oids definitions to phoenix/mman.h

Makefile.host, include/strings.h, string/string.c, sys/rb.c
Added special Makefile for build mininmal libphoenix on host, currently only with rbtree. As main Makefile is prepared for instalation into the toolchain, I think it's cleaner to just have another Makefile.
You can test the build just by typing make -f Makefile.host
Along with this changes, I include two other simple fixes that I found when building libphoenix with host toolchain.
=> Host build

include/sys/ioctl.h
This is required in order to silence warnings when compiling `phoenix-rtos-lwip/port/sockets.c`. They are caused by `lwip` defining the same macros as `libphoenix`. However, the following `lwip` header line could prevent it:
https://github.com/phoenix-rtos/lwip/blob/721dadbba18e7b3da383766373bf8275c690e688/src/include/lwip/sockets.h#L402
if we include necessary definitions before including `lwip/socket.h`. This PR should help with that and provide an ioctl `FIONBIO` definition to user-space programs, which use `libphoenix` headers and not `lwip`.
lwip PR eventually fixing the warnings: https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/17
=> ioctl: Add missing definition required by lwip

stdlib/malloc_dl.c
Currently the least significant 32 bits of the result `nitems * size` are passed to `malloc()` without checking of the most significant bits.
Disassembly for `armv7a7`
Currently:
```
00000000 <calloc>:
0:	b538      	push	{r3, r4, r5, lr}
2:	fb01 f500 	mul.w	r5, r1, r0
6:	4628      	mov	r0, r5
8:	f7ff fffe 	bl	0 <calloc>	8: R_ARM_THM_CALL	malloc
```
After correction:
```
00000000 <calloc>:
0:	b5d0      	push	{r4, r6, r7, lr}
2:	fba0 6701 	umull	r6, r7, r0, r1
6:	2f01      	cmp	r7, #1
8:	bf08      	it	eq
a:	2e00      	cmpeq	r6, #0
c:	d20a      	bcs.n	24 <calloc+0x24>
e:	4630      	mov	r0, r6
10:	f7ff fffe 	bl	0 <calloc>	10: R_ARM_THM_CALL	malloc
```
=> calloc(): corrected checking of the maximum alocated size

include/netinet/in.h
I came across this issue, when developing our ping utility.
Other opt value (e.g. `IP_MULTICAST_TTL`) are already based on lwip values, so I decided to stick with that.
=> netinet: Make IP opt values compatible with lwip

arch/armv7m/reboot.c
This fix enables `psh` to act as expected (do reboot) on imxrt. Additionaly `platformctl` fix in the kernel is required which is available in separate PR (https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/192)
JIRA: RTOS-14
=> imxrt: fix platformctl reboot

unistd/getopt.c
JIRA: RTOS-17
The `opt` variable which causes the warning is always initialized (it's guaranteed by `if (name != NULL)` check) however the compiler still complains. Added explicit `opt = NULL` initialization to get rid of the warning.
=> unistd/getopt: fixed -Wmaybe-uninitialized warning

Makefile
Depending on CFLAGS some ports throw -Wshadow errors on every stdlib
function.
JIRA: CI-45
=> make: bugfix: do not install libc headers into PREFIX_H

sys/uio.c
According to POSIX:
1. If a read() is interrupted by a signal before it reads any
data, it shall return -1 with errno set to [EINTR].
2. If a read() is interrupted by a signal after it has
successfully read some data, it shall return the number of
bytes read.
3. If write() is interrupted by a signal before it writes any
data, it shall return -1 with errno set to [EINTR].
4. If write() is interrupted by a signal after it successfully
writes some data, it shall return the number of bytes written.
JIRA: RTOS-46
Current implementation of readv/writev breaks dropbear (channel write).
=> uio: fix readv & writev return value, set EINVAL errno

arch/armv7m/jmp.S
1. Use ldr instead of addw
2. Add storing mask
3. Fix stack alignment before syscall
1. In the Thumb mode PC points to the address of an executing instruction + 2 next instructions (4 bytes). But, read of PC value in 
`add` instruction is always word-aligned (when instructions are half-word aligned). So, if line `addw r1, pc, #((1f - . - 4) | 1)` is half-word aligned then `r1` has value moved by 2 bytes. (A5.1.2 Reference Manual ARMv7m or [here](https://www.keil.com/support/man/docs/armasm/armasm_dom1361289861747.htm))
2. Just add missing mask store.
3. When pushing context to stack, the hardware saves eight 32-bit words, comprising xPSR, ReturnAddress, LR (R14), R12, R3, R2, R1, and R0. If stack is not aligned to 8 bytes and `CCR.STKALIGN` is set 1 (by default is 1) then additionally …
=> setjmp: fix alignments

include/arch/arm-imx/limits.h, include/arch/armv7/limits.h, include/arch/ia32/limits.h, include/arch/riscv64/limits.h
JIRA: RTOS-59
-Increase ARG_MAX value for all targets
-apply clang-format for limits.h files
Needed for running busybox's test suite (using busybox xargs causes displaying "can't fit single argument within argument list size limit" statement).
Because of SIZE_USTACK value for each target:
-ia32, riscv64, armv7a: (8 * SIZE_PAGE) = 32768
-armv7m: (3 * SIZE_PAGE) = 1536
New values of ARG_MAX are set to:
-32000 for arm-imx, ia32, riscv64
-1500 for armv7
=> include: increase the ARG_MAX value

include/arch/arm-imx/limits.h, include/arch/armv7/limits.h, include/arch/ia32/limits.h, include/arch/riscv64/limits.h, include/dirent.h, include/errno.h, include/stdlib.h, include/unistd.h, sys/stat.c, sys/time.c, unistd/dir.c, unistd/file.c, unistd/sys.c
This change brings real path resolution to Phoenix-RTOS (with '.', '..' and symlinks support (depends on FS used)) with correct errno reporting.
**WARN: This is a breaking change as canonicalize_path_name() works now according to POSIX (which previous implementation was non-conformant with). For internal usage please use either POSIX API or native resolve_path() with extended functionality.**
JIRA: DTR-75
phoenix-rtos/phoenix-rtos-project#113
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/204
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/39
=> Real pathname resolution

stdio/file.c
This makes `fclose(stdin)` possible which is needed by POSIX (eg. busybox
awk does that).
Fixes: phoenix-rtos/phoenix-rtos-project#133
=> file: allocate stdin/stdout/stderr dynamically

include/string.h
According to the Open Group, src argument of bcopy shall be const.
JIRA: RTOS-71
This change makes bcopy() function header compliant to Open Group documentation:
https://pubs.opengroup.org/onlinepubs/007904875/functions/bcopy.html
This fix is needed in order to eliminate compiler warnings, when trying to build e.g. mbedtls using our toolchain.
=> string: Fix bcopy() function header

pthread/pthread.c
DONE: RTOS-72
Enable thread safe errno for pthreads
We need thread safe errno, as most of our code base is multi-threaded
=> pthreads: Enabled thread safe errno

sys/resource.c
setpriority returns negative value on error only
JIRA: DTR-92
This fix is required for new -2 priority set to ps_dcu_app on DATARO. POSIX also specifies that setpriority() should return 0 on success.
=> sys: setpriority/getpriority return value fix

include/arch.h
Fixes phoenix-rtos/phoenix-rtos-project#157
Needed for all variants of `libgcc` for ARM to build correctly (not fail in `./config` due to errors in headers).
Accidentally - brings `libstdc++` compilation much closer to completion.
=> arch: add missing architectures from gcc ARM multilib config

include/arch/riscv64/limits.h, include/arch/riscv64/stdint.h
JIRA: RTOS-77
- change pointer size for riscv64 targets from 32bit to 64 bit
- change size max to 64bit
This removes warnings from phoenix-rtos-tests building (riscv64 targets)
=> include/arch/riscv64: correct sizes from 32bit to 64bit

stdlib/malloc_dl.c
JIRA: RTOS-80
This change makes it possible to safely call realloc() with `size == 0` 0 and `ptr != NULL`.
According to [OpenGroup](https://pubs.opengroup.org/onlinepubs/009696899/functions/realloc.html), `realloc()` should in this case be equivalent to `free()`. This bug caused memory leakage in `getaddrinfo()` function.
- [] Tested by hand on: (list targets here).
=> malloc_dl: Free ptr, when size is equal to 0

unistd/dir.c
JIRA: PD-160
Change in `unistd/dir.c` in `resolve_path()` that fixes some issues with path resolving mainly:
- one character missing leaf
- path with missing branch (e.g `existing/missing/existing/file.txt`)
This PR is a byproduct of `psh` autocompletion PR: 
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/78
`psh` tries to autocomplete path and filenames when `TAB` is used and path validation is done with `resolve_path()`. After changes to `resolve_path` problems occured with autocompletion in `psh`. During adapting `psh` to new `resolve_path()` two major flawes were found:
- resolving path where missing leaf is one character long (e.g resolving path like: `b` or `bin/b`) resulted in wrong resolve
- resolving paths where not a leaf, but part of branch is missing resulted in the …
=> resolve_path: fix one letter leaf resolve

arch/armv7m/jmp.S
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/176
1. `longjmp` now uses `setjmp` context, no need for pc-relative instructions
2. fpu registers are stored in the `env` buffer
3. additionally savesig flag is stored in `env` buffer, thanks to that we can use one `sigsetjmp` function for both `setjmp` and `_setjmp`
=> armv7m: rewrite setjmp

unistd/pwd.c
Changes to `getpwuid` and `getpwnam` functions because of their poor form.  Changes:
- merged common operations into `getpwby()` and `getpwEntry()` static functions
-  char by char reading of `/etc/passwd` instead of broken scanf
- get rid of buffer and reading directly into `struct passwd pwnam`
- no buffer overflow risk
-  check for edge case of function call: `getpnam(NULL);`
Main goal was to reduce stack memory usage and overall fix of memory usage as current implementation is prone to crash. The buffer used to store user entry was too small and using `getpwnam`or `getpwuid` on entry with maxed out (by length) fields will result in not reading all the data. For small targets the stack size is about 4kB and getpwuid by itself must use at least 2,5kB (result of `PATH_MAX`-sized fields) …
=> unistd/pwd: change getpwuid()/getpwnam() functions

include/arch/riscv64/types.h, include/sys/types.h, stdio/file.c, sys/mount.c, sys/stat.c, unistd/dir.c, unistd/file.c
Changes required for LFS (Large Files Support):
- changed `offs_t` definition to `long long` on riscv64 (explicitly state it as a 64-bit type),
- changed `off_t` definition to `off64_t` (`long long`) (explicitly state it as a 64-bit type),
- check `msg.o.attr.err` for errors after sending `mtGetAttr`/`mtSetAttr` messages,
- changed `read()` and `write()` return type to `ssize_t`,
[JIRA: DTR-103](https://jira.phoenix-rtos.com/browse/DTR-103)
[JIRA: RTOS-100](https://jira.phoenix-rtos.com/browse/RTOS-100)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/240
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/141
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/46
https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/43 …
=> Introduce large files support (64-bit off_t type), fix read() and write() return type

include/sys/types.h
Storage device with 512-byte block size and >256GB of storage capacity couldn't be properly represented with `blkcnt_t` and `blksize_t` types.
[JIRA: RTOS-117](https://jira.phoenix-rtos.com/browse/RTOS-117)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/247
=> sys/types.h: change blkcnt_t type to long long

include/arch/arm-imx/stdint.h, include/arch/armv7/stdint.h, include/arch/ia32/stdint.h, include/arch/riscv64/stdint.h, include/stdint.h
JIRA: RTOS-129
Architecture-specific stdint.h headers still lack many definitions. Given that the header itself is C99-mandated, making it more complete by adding missing definitions will increase compatibility mainly with external software.
=> stdint.h: Add missing definitions

syslog/syslog.c
LOG_USR should be a default facility, if a user has not previously
called openlog().
JIRA: DTR-3
This change is neede in order to allow applications like klogd to correctly use syslog() with LOG_KERN facility.
=> syslog: Allow LOG_KERN facility

include/errno.h, include/sys/sockdefs.h
DONE: DTR-209
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/280
https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/32
=> socket: remove custom SOCK_LARGEBUF flag

include/unistd.h
JIRA: CI-100
Nitpick, removing redundant declarations of `getlogin()` and `issetugid`
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/279
=> libphoenix/unistd: redundant declarations of `getlogin()` and `issetugid`

sys/stat.c
`umask()` can't fail, return 0 not to restrict any permission attributes.
[JIRA: DTR-206](https://jira.phoenix-rtos.com/browse/DTR-206)
=> umask: don't restrict process file mode mask until proper implementation is added

stdio/file.c, unistd/dir.c, unistd/file.c
- corrections in errno returned from `resolve_path()` with compliance to posix `resolve()` function
- ~~corrections in errno returned from `open()` with compliance to posix~~ **DROPPED**
- corrections in errno returning from `fopen()` with compliance to posix
- Changes in `resolve_path()` for accordance with documentation:
> The realpath() function shall fail if:
(...)
[EINVAL] The file_name argument is a null pointer.
(...)
[ENOENT] A component of file_name does not name an existing file or file_name points to an empty string.
- ~~Add handling of `path = ""` in `open()` for accordance with:~~ **DROPPED**
> ~~open() shall fall if:
[ENOENT] O_CREAT is not set and a component of path does not name an existing file, or O_CREAT is set and a component of the path prefix of path does not name …
=> unistd/stdio: `resolve_path()`, `fopen()` and `open()` errno fixes

include/sys/stat.h
Added `ALLPERMS` and `ACCESSPERMS` macros (the names are taken from BSD: [link](https://github.com/openbsd/src/blob/4cd1828ed9eeebb6486d183eb7e4a99fc9464b70/sys/sys/stat.h#L151-L153))
Cleaned up file type and permission bits macros (removed octal notation in favour of hexedecimal).
Code that manages file permissions should use provided macros instead of 'magic values', e.g. 0777.
[JIRA: RTOS-148](https://jira.phoenix-rtos.com/browse/RTOS-148)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/288
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/59
=> sys/stat.h: add ALLPERMS and ACCESSPERMS macros, clean up file type and permission macros

unistd/dir.c
Changes fixing:
- errno returned by `rmdir()` when not called on directory
- errno returned by `chdir()` when not called on directory
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/287
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/288
=> fixing errno of `rmdir()` and `chdir()` when not called on a directory

include/string.h, string/string.c
JIRA: PD-189
Two functions that are BSD-based: `strlcpy()` and `strlcat()` implemented in libphoenix for better micropython port compatibility. 
Phoenix-RTOS supports micropython port which internally uses both `strlcpy()` and `strlcat()` functions. Their source code is artificially added do codebase via patches. This PR aims to reduce patches by implementing these functions in libphoenix.
`strlcpy()` and `strlcat()` short description:
> The strlcpy() and strlcat() functions copy and concatenate strings respectively. They are designed to be safer, more consistent, and less error prone replacements for strncpy(3) and strncat(3). Unlike those functions, strlcpy() and strlcat() take the full size of the buffer (not just the length) and guarantee to NUL-terminate the result (as long as size …
=> string: add strlcat() and strlcpy() implementation

unistd/dir.c
- unistd/dir: fix readdir(), when reading file with NAME_MAX name length
Fixes: phoenix-rtos/phoenix-rtos-project#397
DONE: RTOS-125
=> unistd/dir: fix readdir(), when reading file with NAME_MAX name length

stdlib/strtoul.c
- stdlib: strtol: change return type to long int from int
- `strtol()`, `strtoul()` definitions incompatible with declarations.
=> - stdlib: strtol: correct return type in definitions

pthread/pthread.c
- Fixes stack memory leak after pthread_join
JIRA: RTOS-205
=> pthread: fix missing stack free after thread join

stdlib/malloc_dl.c, stdlib/malloc_trivial3.c
SUSv2 requires `malloc()`, `calloc()`, and `realloc()` to set `errno` to `ENOMEM` upon failure. Applications that check `errno`
on a `NULL` result without setting this value behave unexpectedly.
JIRA: RTOS-222
=> malloc: let malloc set errno

include/pthread.h, include/sys/types.h, pthread/pthread.c
- Implements pthread conditions in libphoenix
JIRA: RTOS-179
=> pthread: implement conditionals

include/stdio.h
Too low value causes bad dmesg fragmentation, as new line is added on each fflush
JIRA: RTOS-194
Too low value causes frequent klog fragmentation that cannot be fixed otherwise.
=> stdio: Increase BUFSIZ on NOMMU targets

stdio/perror.c
DONE: RTOS-229
Note: right now strerror gives just errno define name - good enough for debugging, not so for full *NIX experience.
=> Add perror implementation

unistd/sysconf.c
- unistd: fix _SC_OPEN_MAX value returned by sysconf()
DONE: RTOS-240
Required for running posix test suite.
=> unistd: fix _SC_OPEN_MAX value returned by sysconf()

_startc.c, pthread/pthread.c
Add locking to global structs that can be written and read.
- JIRA: RTOS-225
=> make pthread thread safe

include/arch/riscv64/types.h
- include: riscv64: types.h: define ssize_t as long instead of int
- DONE: RTOS-87
=> include: riscv64: limits.h: correct SSIZE_MAX macro

unistd/getopt.c
- added condition to check optind <= 0
- improved handling of options --
- for return getopt() to initial state set optind = 0
=> unistd/getopt.c: fix getopt() function

include/stdio.h, stdio/fprintf.c
This change:
- removes temporarily allocated memory by `dprintf()`,
- adds `vdprintf()`,
- adds error handling to `fprintf()`, `vfprintf()` which operates on the file stream and to `vdprintf()`, `dprintf()` which operates on the file descriptor.
JIRA: RTOS-277
=> Add error handling to fprintf and reduce memory usage of dprintf

include/sys/threads.h, pthread/pthread.c
JIRA: RTOS-226
`pthread_join` now calls threadJoin with specific thread id
- JIRA: RTOS-226
=> pthread_join: call threadJoin with specific id

include/stdio.h
Adds mising prototypes of the following functions getdelim(), vfscanf(), vscanf(), vsscanf()
Fixes issue: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/583
JIRA: RTOS-323
=> stdio: Add missing prototypes

stdio/scanf.c
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/608
JIRA: RTOS-366
=> stdio/scanf: Fix `%z` length modifier

stdio/scanf.c
Adds `%` (aefgAEFG) conversion support and `L` length specifier for `floats`, `doubles`, `long doubles`.
Fixes issue:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/604
Note: This implementation depends on `strto(f|d|ld)` implementation for validation and parsing the input.
For hexadecimal fractional notation and NAN, INFINITY parsing support
refer to the [libphoenix/stdlib/strtod.c:`strto_any()`](https://github.com/phoenix-rtos/libphoenix/blob/961a7db311e2c4c880c372a6502b499a683f09d6/stdlib/strtod.c#L38-L39) implementation.
JIRA: RTOS-364
https://github.com/phoenix-rtos/libphoenix/pull/231
=> scanf: add `%f` (aefgAEFG) conversion support and `L` length specifier.

unistd/file.c
Remove obsolete `#if NOMMU .. #endif` in `isatty()` which is verified to work on all supported non-mmu targets which include:
* i.MX RT 117x, 106x
* stm32l4a6
The value returned by termios function `tcgetattr()` is correct in all cases on non-mmu targets if tried to open either tty or non-tty device. Function `tcgetattr()` sends `ioctl()` which is wrapped in a `mtDevCtl` message to the `libtty` (uart, console) driver. It will fail if the driver does not speak `libtty`.
JIRA: RTOS-369
=> unistd/isatty: Fix `isatty()` on NOMMU arch

stdlib/strtoul.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/603
This change refactors implementation of `strtoul()` in the following way
* the function returns either the result of the conversion or, if there was a leading minus sign the negation of the result of the conversion represented as an unsigned value unless the original (non-negated) value would overflow.
* in the latter case the `strtoul()` function returns `ULONG_MAX` and sets `errno` to `ERANGE`.
* any white space before the number is eaten.
* in case base value is unsupported errno is set to `EINVAL`.
* in case of no conversion was performed `EINVAL` errno is set.
JIRA: RTOS-367
=> stdlib/strtoul: Refactor implementation

stdio/Makefile, stdio/bignum.c, stdio/bignum.h, stdio/format.c
- Remove invalid code that prints float
- Extract floating point printing to a new function
- Add support for conversion specifiers: %f, %F, %e, %E, %G, %a, %A
- Add support for flag: '-'
- Fix: Sign flag now works for positive values.
- Fix: double argument representing infinity is printed as 'inf' for %f, %e and %g conversion specifiers and as 'INF' for %F, %E and %G
- Fix: double argument representing NaN is printed as 'nan' for %f, %e and %g conversion specifiers and as 'NAN' for %F, %E and %G
- Fix: %g conversion specifier now doesn't ignore field width for {0.0, -0.0, NaN, infinity}
- Fix: conversion specifier %c used to ignore minimum field width
- Fix: conversion specifier %s used to truncate strings to minimum field width, instead of precision
DONE: RTOS-318
=> stdio/format: Fix printf %{g, s, c}. Add %{G, f, F, e, E, a, A}

stdlib/env.c
`unsetenv()` should `return -1` and set `errno` to `EINVAL` when empty string is passed as argument.
JIRA: RTOS-402
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/631
=> stdlib: Fix unsetenv("") 

stdio/format.c
JIRA: RTOS-318
Change incorrect return type, caused by automatic rebase.
=> format: Fix an error caused by automatic rebase.

stdlib/rand.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/708
Makes `__randseed` variable `static`, and assigns it initial value of `1` as it is said in POSIX:
> If `srand()` is not called, the `rand()` seed is set as if `srand(1)` was called at program start.
JIRA: RTOS-445
=> stdlib: fix initial seed for rand()

include/pthread.h
This PR adds declaration of `pthread_attr_setstack` and `pthread_attr_getstack` function to header `pthread.h`. They were implemented previously, but not included in header.
Ability to use already defined functions.
=> Add missing `pthread_attr_setstack` and `pthread_attr_getstack` to header

stdio/file.c
There is no relevance between getdelim default buffer size and default size of stream buffer size. Made getdelim default buffer size 120 bytes, as it's a most common value.
DONE: RTOS-501
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/753
=> stdio: Reduce default getdelim buffer size

unistd/dir.c
Main point of this is to remove `char tmp_buf[PATH_MAX];` from stack. I refactored rest of the function to make it (hopefully) easier to read. 
This should give same output as before. Only change is case of empty symlink as it was setting errno to 0.
=> refactor path resolving

unistd/getopt.c
Adds support for `getopt` extension: option characters followed by two colons.
A character followed by a `single colon` indicates that an argument is to follow the option on the command line.` Two colons` indicates that the argument is optional (this is transparent extension `not covered by POSIX`).
The extension is present in BSDs ([1](https://man.openbsd.org/getopt.3), [2](https://man.freebsd.org/cgi/man.cgi?getopt(3))) and GNU.
`getopt(argc, argv, "a::b:X")`
In the string above, option a will accept an optional argument. (Option requires an argument) Usage:
|Option syntax |Meaning |
| --- | --- |
|`-a` | OK, No argument provided (optional). |
|`-afoo` | OK, option `a` optional argument is `foo` |
|`-a` `foo` | Wrong, `no space allowed` with optional arguments, `foo` is `considered a …
=> getopt: add support for :: optional arguments

include/sys/ioctl.h
=> Fix wrong mask value in ioctl.h

include/arch/arm-imx/arch.h, include/arch/armv7/arch.h, include/arch/ia32/arch.h, include/math.h, math/power.c
DONE: RTOS-495
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/738
To provide simple, platform independent and hw accelerated if possible implementation of sqrt()
=>  math: Add optional per arch sqrt implementation 

include/complex.h, math/Makefile, math/complex.c
Provide required `complex.h` function prototypes and commonly used functions.
`cabs()` and `cabsf()` implementations, to calculate distance, temporarily uses `sqrt()` instead of `hypot()` which is required but missing now.
In `cexp()` implementation Euler equation is used.
In reference to https://github.com/phoenix-rtos/phoenix-rtos-project/issues/785
JIRA: RTOS-528
=> complex: add commonly used complex number funcs

include/errno.h
Remove EDEADLK definition - now defined through installed kernel header
JIRA: RTOS-543
=> errno: remove EDEADLK definition

ctype/ctype.c, include/ctype.h
DONE: RTOS-549
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/782
=> ctype: Provide fast macro implementation

include/sys/socket.h
DONE: RTOS-546
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/781
=> socket: Align struct sa_familty to allow safe casting between all sockaddr_*

include/string.h, string/strerror.c
DONE: RTOS-554
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/694
=> string: strerror_r() implementation

arch/riscv64/_start.S
=> riscv64: load args to main in _start

include/arch/ia32/arch.h
This change assumes that the `fsqrt` calculation is performed for double precision FP and rounded to the nearest (even) value. To achieve this, the FPU control word is set accordingly at the sqrt computation time. ~~All exceptions are enabled: any underflow, overflow, /0, invalid precission, etc during sqrt calculation will throw an exception.~~
All other settings (exceptions mask, infinity control) in FPU control word are inherited (not changed).
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/800
JIRA: RTOS-562
=> math: Fix sqrt calc on IA32

include/unistd.h, unistd/sysconf.c
Portable applications should employ `sysconf(_SC_PAGESIZE)` instead of `getpagesize()`. Most systems allow the synonym `_SC_PAGE_SIZE` for `_SC_PAGESIZE` (both are specified in POSIX).
This change also replaces enums `_SC_*` with the corresponding definitions, and fixes the ambiguity of the previously defined `_SC_PAGESIZE` which overlapped the `_SC_IOV_MAX` enumeration.
JIRA: RTOS-577
=> unistd: add _SC_PAGESIZE entry to sysconf

termios/termios.c
errno is set by ioctl, termios functions should not fail on EINTR
JIRA: RTOS-585
=> termios: Fix EINTR and errno handling

Makefile, Makefile.host
Not needed since a long time.
JIRA: CI-334
CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/823
=> make: remove direct target-arch include

include/stdio.h
DONE: RTOS-599
Fixes https://github.com/phoenix-rtos/libphoenix/issues/250
=> stdio.h: Remove duplicated ungetc() prototype

include/dirent.h
- already used internally in jffs2
- not part of POSIX but needed for interoperability with GNU tools
- (especially autoconfig/automake in libstdc++ gcc-9.5.0)
JIRA: CI-334
=> dirent: use common d_type defines

time/time.c
Before this fix `time()` function rounded timestamps to the nearest second, while other functions like `gettimeofday()` rounded it down. As a result, it was possible to get different timestamps for the same second depending on what function was used.
Changes rounding in `time()` function to be in line with other functions that retrieve the current time.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/621 - issue was caused by `date` command using `time()` and `touch` command using `gettimeofday()` to get the current time - but the two functions returned unexpectedly different results.
=> time: fix incorrect rounding in time()

time/time.c
Timestamps that were far into the future (beyond about year 14000) were parsed incorrectly because the previous algorithm assumed too many leap years.
Related to https://github.com/phoenix-rtos/phoenix-rtos-project/issues/801 - in one example time on RTC was set correctly to maximum timestamp minus the given number of seconds, but displayed incorrectly due to this bug.
=> Fix bug in formatting timestamps with gmtime_r

arch/armv7a/signal.S, arch/armv7m/signal.S, arch/ia32/signal.S, arch/riscv64/signal.S, arch/riscv64/syscalls.S, arch/sparcv8leon3/signal.S, signal/signal.c
Rework signal handling:
- Signal context is now prepared on user stack
- Return from signal handler is done through new `sigreturn` syscall
- Implement signals on `sparcv8leon3`, `riscv64` and `armv7m*` targets
JIRA: RTOS-539
=> rework signal handling

Makefile, ubsan/Makefile, ubsan/ubsan.c
Provides small but full implementation of C runtime handlers for the undefined behavior sanitisation mechanism.
The output log is only colored when printing to a tty device, if the output is a file the log will be plain text.
The goal of the implementation is to provide a minimalist implementation of ubsan that can be run on small targets, that's why this implementation does not provide C++ instrumentation and other handlers like:
`uptr __ubsan_vptr_type_cache[];`
`void __ubsan_handle_dynamic_type_cache_miss(..);`
`void __ubsan_handle_dynamic_type_cache_miss_abort(..);`
Buggy snippet used in this example
```C
int main(int argc, char **argv)
{
unsigned int v = 1 << 31;
int tab[] = { 0 };
return (tab[argc] != v) ? 0 : 1;
}
```
imxrt117x (ubsan implementation from this PR):
ia32-generic …
=> ubsan: provide C handlers for libubsan

include/sys/types.h, pthread/pthread.c
JIRA: RTOS-639
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/876
=> pthread/cond: Use clock_id from condattr

posix/stubs.c
Functions using ttyname_r were experiencing out-of-bounds errors.
(eg. `login` from `busybox`)
JIRA: RTOS-640
=> stubs: fix ttyname_r

pthread/pthread.c
=> libphoenix: fix mutexing in pthread_create

include/assert.h, include/stdlib.h, stdlib/abort.c
- atexit functions should not be called
- stream synchronization is optional (might lead to deadlocks)
- the exit code should indicate the program was killed with SIGABRT
JIRA: RTOS-668
=> assert: use abort() instead of exit()

stdlib/mktemp.c
DONE: RTOS-670
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/911
=> mktemp: Fix wrong divisor value for modulo operation

include/sys/mman.h, pthread/pthread.c, stdio/file.c, stdlib/malloc_dl.c, stdlib/malloc_trivial3.c
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/471
=> Adjust mmap to new interface

arch/sparcv8leon3/reboot.c, arch/sparcv8leon3/syscalls.S, include/arch/sparcv8leon3/arch.h
=> sparcv8leon3: add GR712RC target

include/sys/mman.h
JIRA: RTOS-666
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/475
=> Add mprotect syscall

unistd/file.c
JIRA: RTOS-397
tested in: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/939
=> lseek: Adapt to change in kernel API

arch/ia32/syscalls.S
=> ia32/vfork: simplify assembly

arch/ia32/syscalls.S
=> vfork: do not use hard coded 4 for performing syscalls

include/arch/sparcv8leon3/arch.h
=> sparcv8leon3: add hw-accelerated sqrt implementation

unistd/crypt.c
Previously data passed to `base64_encode` was casted directly from `unsigned int` to `unsigned char` array.
This PR fixes this by explicitly copying appropriate values of the bytes.
Hash is always base64-encoded as little endian.
=> unistd/crypt: fix hash byte order

math/common.c
DONE: RTOS-761
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/994
=> math/common.c: Fix incorrect use of the address operator

stdlib/malloc_dl.c
JIRA: RTOS-769
Fix overflow check on 64-bit targets, where `size_t * size_t` may not fit in `uint64_t`.
Division gets optimized by the compiler.
=> stdlib/calloc: fix size overflow check

string/string.c
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1005
=> strings/ffs: avoid possible recursion

include/arch/armv7a/setjmp.h, include/arch/armv7m/setjmp.h, include/arch/ia32/setjmp.h, include/arch/riscv64/setjmp.h, include/arch/sparcv8leon3/setjmp.h
Add `aligned` attribute to `packed` `__jmp_buf` struct
Misalignment caused abort exception on zynq7000
=> include/setjmp: add alignment to `__jmp_buf` definition

include/sys/events.h, include/sys/file.h
=> sys: remove duplicate kernel definitions from events.h & file.h

arch/arm/memcpy.S
JIRA: RTOS-789
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/526#discussion_r1518903706
=> arm/memcpy: optimize register usage

Makefile, include/phoenix/attribute.h, include/sys/file.h, include/sys/ioctl.h, phoenix/Makefile, phoenix/attribute.c, sys/events.c, sys/ioctl.c, sys/mount.c, sys/socket.c, sys/stat.c, sys/statvfs.c, sys/time.c, unistd/dir.c, unistd/file.c
This PR adapts `libphoenix` to msg API changes.
There is only 1 breaking change in this PR: `mount_i/o_msg_t`:
- `oid_t dev` is removed from `mount_i_msg_t`
- `int err` is removed form `mount_o_msg_t`
=> msg API changes

unistd/getopt.c
Change needed to be symmetric with getopt() implementation.
JIRA: RTOS-850
=> getopt: fix getopt_long resetting on optind <= 0

include/net/if_arp.h, include/net/ip6_route.h, include/net/route.h, include/netinet/icmp6.h, include/netinet/in.h, include/sys/sockdefs.h
Adding features needed to compile and run ifconfig and ping with IPv6 on Busybox.
* `net/ip6_route.h` is there for Busybox `route.c` to compile when IPv6 is enabled. The routes for IPv6 are not implemented yet.
* `netinet/icmp6.h` is essential for ping in Busybox to work
* changes in `netinet/in.h` and `sys/sockdefs.h` are used by ping in Busybox
* changes in `net/route.h` are there so that route in Busybox compiles
* changes in `net/if_arp.h` are there so that ifconfig in Busybox compiles
=> Add support for IPv6

arch/arm/Makefile, arch/arm/v8m/Makefile, arch/arm/v8m/reboot.c, arch/arm/v8m/syscalls.S, arch/arm/v8m/tls.c, include/arch.h, include/arch/armv8m/arch.h, include/arch/armv8m/limits.h, include/arch/armv8m/setjmp.h, include/arch/armv8m/stdint.h
JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
=> Add armv8m architecture support

stdlib/exit.c
JIRA: RTOS-899
Previously anything written in atexit function wasn't guaranteed to get flushed at the end of execution.
=> fix(exit): fflush after calling atexit handlers

include/arch/armv7a/arch.h, include/arch/armv7m/arch.h, include/arch/armv8m/arch.h, include/arch/armv8r/arch.h, math/power.c
Declaring functions using double and float on arm in arch.h caused the definitions to spread to unexpected places. This deemed using "general-regs-only" in unit using basically anything from libphoenix impossible. Example of such unit is unwind-arm.c in libgcc for arm.
Declared as compound expressions to enforce inlining.
JIRA: RTOS-914
=> arm: convert __ieee754_sqrt(f) to macros

sys/select.c
select() should fail with -1 and set errno to:
* EBADF when one or more of the fdsets specified an invalid fd
* EINVAL if nfds is incorrect and/or if timeout makes no sense (i.e. tv_usec is outside of [0, 999999])
JIRA: RTOS-945
=> sys/select: fix errnos

time/time.c
This var could be uninitialized only when sizeof(periods) == 0, which is not true: false-positive
DONE: RTOS-943
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1124
=> time: Fix overzealous warning on -Og

include/stdio.h, stdio/file.c, unistd/file-internal.h, unistd/file.c
=> stdio/file: fix numerous issues in the fread/fwrite functions

include/assert.h
=> libphoenix: make assert macro posix compliant

stdlib/strtoul.c, stdlib/strtoull.c
Add errno setting in `strto{u}ll`, fix minor bugs in `strto{u}l`. Details in commit messages.
Closes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/543
=> stdlib: improve string to integer conversion functions

stdio/scanf.c, stdlib/strtod.c
* `strtof`, `strtod` and `strtold` can parse infinity and NaN string representations, as well as hexadecimal floating point representations
* Code size was reduced by extracting operations done multiple times into functions.
* Performance of `strtof` and `strtod` was improved. Now `uint64_t` is used as an intermediate container for digits that were read, instead of `long double` used previously. This reduces the number of `long double` multiplications necessary.
* Reading of floating point numbers in `scanf` was reworked, fixing some bugs and improving performance (e.g. previously the conversion was performed twice, with one result being discarded).
* Fix buffer over-read bug in `scanf` for `%c` format.
Fix https://github.com/phoenix-rtos/phoenix-rtos-project/issues/634, …
=> stdlib, stdio: improve float string parsing

unistd/dir.c
In some cases an invalid errno set in _readlink_abs() propageted outside the function
JIRA: RTOS-981
=> unistd: fix _resolve_abspath() errno setting

include/math.h, math/common.c, math/common.h, math/exp.c, math/hyper.c, math/power.c, math/trig.c
=> math: improve POSIX compliance

include/termios.h, include/unistd.h
=> !unistd.h: move _POSIX_VDISABLE from termios.h

include/arch/sparcv8leon/limits.h
JIRA: RTOS-1010
psh tests create a file with name length of 90, which exceeded NAME_MAX define - which is not checked properly in libphoenix.
=> arch/sparcv8leon: increase PATH_MAX and NAME_MAX values

include/sys/file.h, include/sys/statvfs.h, include/sys/types.h, sys/statvfs.c
Introduced sys_statvfs syscalls handling both statvfs anf fstatvfs.
JIRA: RTOS-965
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/631
=> sys: implement fstatvfs

include/pthread.h, include/sys/types.h, include/unistd.h, pthread/pthread.c, string/string.c, sys/socket.c
=> misc: adapt to gcc 14.2

stdlib/atexit.c, stdlib/exit.c
JIRA: RTOS-900
__cxa_finalize support is needed for shared libs support
=> exit: change _atexit_call into __cxa_finalize

include/sys/socktypes.h
Some external program eg mbedtls check for those defines to checks if a type is available.
JIRA: RTOS-1027
=> socktypes.h: define _SOCKLEN_T

Makefile, arch/aarch64/Makefile, arch/aarch64/crt0.S, arch/aarch64/jmp.S, arch/aarch64/memcpy.S, arch/aarch64/memset.S, arch/aarch64/reboot.c, arch/aarch64/signal.S, arch/aarch64/syscalls.S, include/arch.h, include/arch/aarch64/arch.h, include/arch/aarch64/limits.h, include/arch/aarch64/setjmp.h, include/arch/aarch64/stdint.h, include/arch/setjmp.h, include/math.h, math/exp.c
Port libphoenix to AArch64 architecture and Zynq Ultrascale platform.
=> hal: AArch64/ZynqMP port

include/arch/armv7a/arch.h, include/arch/armv7m/arch.h, include/arch/armv7r/arch.h, include/arch/armv8m/arch.h, include/arch/armv8r/arch.h, include/arch/ia32/arch.h, include/arch/riscv64/arch.h, include/arch/sparcv8leon/arch.h, regex/regcomp.c, ubsan/ubsan.c
There are some useful warning flags, which are enabled in internal projects, like `-Wundef` and `-Wshadow`.
This commit allow libphoenix to be build with -Wundef without warnings
To enable `-Wundef` flag in the future
=> Fixes to allow enabling -Wundef

arch/aarch64/signal.S
Previous solution resulted in stack not being aligned to 16. Qemu doesn't check stack alignment correctness due to performance reasons - that's why it passed the tests.
JIRA: RTOS-1059
=> signal: fix signal trampoline for aarch64

unistd/alarm.c
- fix alarm() return value to match POSIX requirement of returning nonzero value if alarm is set.
- fix after fork alarm thread by spawning new ib atfork handler
Resolves phoenix-rtos/phoenix-rtos-project#1241
=> unistd/alarm: fix alarm() after fork

Makefile, stdio/format.c, stdio/scanf.c
https://github.com/phoenix-rtos/libphoenix/pull/437
https://github.com/phoenix-rtos/libphoenix/pull/370 - scanf part
https://github.com/phoenix-rtos/libphoenix/pull/357
=> Backport io changes (possibility of disabling float and scanf fixes) to 3.2
