- stdlib/env.c
- string/string.c
only first delimiter character was used, removed unused count variable
> strsep delimiter fix

- unistd/getopt.c
Required for parsing long options (e.g. --color for ls).
> unistd: added getopt_long implementation

- math/power.c
Previous sqrt() implementation is slow and
in frequent use can become a bottleneck.
Current implementation uses reciprocal square
root algorithm (similar to Newton Rhapson method
but without division which is faster) and takes
advantage of IEEE 754 double convention. The
implementation is about 12.5 times faster than
previous one, but about 1.75 times slower than
libm's (time complexity tests done by looping
100000 times through 10 known square roots).
> math: change sqrt() implementation

- include/sys/threads.h
This PR is associated with https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/160
> sys: add program execution from syspage

- Makefile
- _startc.c
- misc/Makefile
- misc/fini.c
- misc/init.c
- stdlib/exit.c
This PR depends on changes in kernel: https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/191
> libphoenix: add contructors and destructors

- stdio/sprintf.c
According to POSIX specification:
"Upon successful completion, the snprintf() function shall return
the number of bytes that would be written to s had n been
sufficiently large excluding the terminating null byte."
"If the value of n is zero on a call to snprintf(), nothing shall
be written, the number of bytes that would have been written had n
been sufficiently large excluding the terminating null shall be
returned, and s may be a null pointer."
JIRA: RTOS-24
> stdio: snprintf(), vsnprintf() return value fix

- include/getopt.h
> include/getopt.h: add getopt_long()

- include/string.h
- string/strdup.c
> string: add strndup

- include/net/ethernet.h
- include/netpacket/packet.h
- include/sys/socket.h
> socket: add packet sockets definitions

- include/limits.h
- include/sys/syslimits.h
- include/sys/uio.h
- include/unistd.h
- sys/Makefile
- sys/uio.c
- unistd/sysconf.c
> uio: add readv, writev, IOV_MAX, _SC_IOV_MAX

- include/string.h
> string: add legacy bcopy

- include/net/if.h
> net: add IF_NAMESIZE define

- string/string.c
JIRA: RTOS-62
Implementation of strncat.
strncat is used by lighttpd, sscep and dropbear.
> string: add strncat

- include/errno.h
JIRA: DTR-6
Required for IPSEC driver.
> errno: add EPROTOTYPE

- stdio/file.c
According to POSIX the mode argument should be allowed by the file
access mode of the FD (not necessarily exactly the same). Also
truncation and appending should be ignored.
Also:
- added relevant errnos
- removed other bug (closing provided fd in case fdopen fails())
Fixes phoenix-rtos/phoenix-rtos-project#136
> file: fix fdopen mode checks

- stdio/file.c
JIRA: RTOS-59
-add returning eof and converting to char for a few functions in file.c
-apply clang-format for file.c
It's needed for busybox test suite run and fixes the following issue:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/143
> stdio: add returning eof and converting to char for a few functions in file.c

- include/net/ethernet.h
- include/netpacket/packet.h
- include/phoenix/if_ether.h
Also:
- format code
- switch from ETHERTYPE_ALL to ETH_P_ALL
JIRA: DTR-94
Required for netdump.
> socket: add missing packet sockets definitions

- stdio/format.c
> stdio: add support for %jd and %ju format specifiers

- time/time.c
> time: set errno in clock_gettime

- include/sys/un.h
> socket: add SUN_LEN macro

- include/sys/socket.h
> socket: fix CMSG_* macros

- unistd/dir.c
According to POSIX `realpath()`, `readlink()`, `opendir()` and `rmdir()` can't exit with `errno=EINTR`. Retry
lookup() until succeeded.
Stop-gap for phoenix-rtos/phoenix-rtos-project#188.
Fixes most common error path (interrupted open() in busybox ash).
- phoenix-rtos/phoenix-rtos-project#188
- JIRA: DTR-154
> realpath: fix handling lookup interrupted call

- math/trig.c
arctan(x) = - pi / 2 - arctan(1/x) if x < 0
arctan(x) = pi / 2 - arctan(1/x) if x > 0
In our case x is always bigger than 0, as we removed sign `s` earlier. Therefore compute value for positive x and apply sign at the end (because tan(-x) = -tan(x)).
> math: fix atan for x < -1.0

- syslog/syslog.c
JIRA: RTOS-127
Fix for https://jira.phoenix-rtos.com/browse/RTOS-127
> sys/syslog: print message to stderr if sendto fails

- unistd/dir.c
Fix rmdir() usage in mount points context.
[JIRA: DTR-180](https://jira.phoenix-rtos.com/browse/DTR-180)
> unistd/rmdir: fix lookup() usage, don't remove active mount points

- unistd/sys.c
Fixes: phoenix-rtos/phoenix-rtos-project#186
> exec: correctly resolve shebang scripts in PATH

- stdio/file.c
Fixed append mode flags. See "a" mode on [opengroup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html)
[JIRA: RTOS-133](https://jira.phoenix-rtos.com/browse/RTOS-133)
> stdio/file.c: fix append mode flags (add O_WRONLY)

- unistd/file.c
Added POSIX compliant behaviour for open(), fopen() and freopen() on a directory.
[JIRA: RTOS-132](https://jira.phoenix-rtos.com/browse/RTOS-132)
> unistd/file.c: open() on a directory with write access - set errno to EISDIR

- arch/armv7a/reboot.c
- arch/armv7m/reboot.c
- arch/ia32/reboot.c
- arch/riscv64/reboot.c
- include/sys/reboot.h
- sys/mount.c
- add `reboot_reason()` per-arch API
- support paths  resolving in `mount()`
JIRA: DTR-181
> add reboot_reason, fix mount paths resolving

- include/paths.h
This change is needed in order to provide API for userspace programs to kernel log buffer.
> paths: Add _PATH_KLOG definition

- unistd/sys.c
JIRA: PD-213
Added check in `execv()` function that checks if path (after resolving) leads to a regular file as it is possible to _execute a directory_ which is nonsense
Issue from which this PR arised:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/248
As stated in documentation:
> The exec family of functions shall replace the current process image with a new process image. The new image shall be constructed from a regular, executable file called the new process image file.
So i added check via `stat()` if resolved path is indeed regular file.
> execv: check if file is executed

- include/paths.h
> paths: Add _PATH_CONSOLE definition for system console path

- include/sys/sockdefs.h
> socket: add custom SOCK_LARGEBUF flag

- include/sys/file.h
- sys/stat.c
Add new attribute types which allow to retrieve number of allocated 512-byte blocks and optimal I/O size access for a given file.
[JIRA: DTR-205](https://jira.phoenix-rtos.com/browse/DTR-205)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/283
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/56
> sys/stat: add 'atBlocks' and 'atIOBlock' attributes for setting statst_blocks and stat.st_blksize fields

- net/inet_ntop.c
- syslog/syslog.c
> Fixed warnings

- stdio/file.c
JIRA: PD-235
- Adding necessary file closing if `fopen()` fails to allocate memory after `safe_open()`
- move `mode == NULL` check to `string2mode()`
- accompany `string2mode()` change with correct errno returned when used
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/298
> fopen(): fix closing and errno

- stdio/file.c
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/274
JIRA: PD-240
- remodel code of `getline()` where it handles not initialized buffer and too small size so that:
- it does not `free()` buffer for no reason if it is too small to hold read line and `realloc()` fails
- it does not change `*n` if buffer is not resized (memory masking from issue)
- after successful getline `*n` was too small by one 
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/274
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/73
> getline(): correct size handling + little refactor

- posix/stubs.c
- unistd/file.c
[JIRA: DTR-250](https://jira.phoenix-rtos.com/browse/DTR-250)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/292
> unistd/file.c: add fsync() implementation

- stdio/scanf.c
> stdio: add support for 'j' and 'z' argument types in scanf

- sys/time.c
JIRA: DTR-276
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/62
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/304
> time: add utimes(), lutimes() and futimes() implementation

- stdio/asprintf.c
> stdio: fix vasprintf return value

- include/sys/file.h
- include/sys/statvfs.h
- include/sys/types.h
- sys/Makefile
- sys/statvfs.c
Added new filesystem message type (`mtStat`) and `statvfs()` implementation.
[JIRA: DTR-100](https://jira.phoenix-rtos.com/browse/DTR-100)
> sys/statvfs: add statvfs() implementation

- include/arch/arm-imx/stdint.h
- include/arch/armv7/stdint.h
- include/arch/ia32/stdint.h
- include/arch/riscv64/stdint.h
- include/inttypes.h
- include: inttypes: add SCN defines
JIRA: PD-272
`SCNU64` macro needed in mbedtls incoming port.
> include: inttypes: add SCN defines

- include/math.h
- include/netinet/tcp.h
- include/pthread.h
- include/stdlib.h
- stdlib/strtod.c
- include: add pthread_exit() missing declaration
- include: add TCP_KEEPIDLE and TCP_KEEPINTVL to tcp.h
- stdlib: add strtof()
- include: apply clang-format to math.h
- include: add isnan(), isinf() and signbit() macros to math.h
Macros/functions that are used in azure sdk and may be useful in other incoming ports.
JIRA: PD-251
> Add macros/functions required for azure iot sdk c

- Makefile
- include/wchar.h
- wchar/Makefile
- wchar/wchar.c
- wchar: add wcscmp implementation
- include: add mbstate_t and wcslen, wcstombs declarations
Mentioned functions' declarations are required for azure iot sdk c incoming port building.
DONE: PD-285
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/120/files
> wchar: add wcscmp implementation and declarations required for azure sdk

- include/wchar.h
- include/wchar: add wcsrtombs() declaration
Needed for azure sdk port
JIRA: PD-285
> include/wchar: add wcsrtombs() declaration

- time/time.c
- unistd/sys.c
> Implement nanosleep(), fixes in sleep() and usleep()

- include/pthread.h
- include/sys/types.h
- pthread/pthread.c
Implements functions required for running posix test suite
- JIRA: RTOS-236
> pthread: implement missing functions

- pthread/pthread.c
JIRA: RTOS-236
fix warnings introduced in JIRA: RTOS-236
> libphoenix: fix warnings

- unistd/sys.c
The child process created by vfork contains the same memory map as the parent. Only if an error occurs, the execve function returns. This commit fixes memory leaks in execve function to free the memory allocated on the parent's map.
RTOS-174
close  https://github.com/phoenix-rtos/phoenix-rtos-project/issues/371
> unistd/sys.c: fix memory leak in execv invoked after vfork

- stdio/fprintf.c
In the current code, if the `write()` function sets the `errno` variable to the value `EINTR` there will be an exit from the `while` loop, and I guess this loop in such case should be contine.
What remains to be considered is what to do in case the `write()` function returns a value of `0`.
> fprintf.c: fix handling of the variable returned by the write() function

- stdio/fprintf.c
Handle undefined behavior when `wlen = write(.., todo)` returns `wlen == 0` while `todo != 0`. I assume `EIO` for `errno` as it is closest to that some kind of hardware level error occurred. It's also possible that the application tried to perform some operation that is not possible because the device is in wrong state.
JIRA: RTOS-279
> fprintf: Handle case when write returns zero length

- include/sys/threads.h
JIRA: RTOS-267
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/536
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/158
https://github.com/phoenix-rtos/plo/pull/215
https://github.com/phoenix-rtos/libphoenix/pull/210
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/348
> Adapt to change in spawnSyspage API

- pthread/pthread.c
JIRA: RTOS-288
fixes `pthread_once` deadlocking
JIRA: RTOS-288
> pthread: fix pthread_once mutex locking

- stdio/file.c
- stdio/scanf.c
JIRA: RTOS-221
Fixes the following issues:
- https://github.com/phoenix-rtos/libphoenix/issues/116
- https://github.com/phoenix-rtos/libphoenix/issues/115
- https://github.com/phoenix-rtos/libphoenix/pull/191
> Fix `getline()` and implement `scanf()` to work with `stdin`

- stdio/file.c
- POSIX incompliance. 
- If the end-of-file indicator for the input stream pointed to by stream is not set and a next byte is present, the fgetc() function shall obtain the next byte as... (fgetc)
- The clearerr() function shall clear the end-of-file and error indicators for the stream to which stream points.
> stdio: handle EOF in fgetc_unlocked() and clearerr()

- stdio/file.c
> stdio: apply MISRA braces convention in file.c

- include/stdio.h
DONE: RTOS-302
Changed default stream size for NOMMU platform to 80B
This change is good for klog implementations to have wider default log line. Some of existing logs was moved to the new line without that. Downside of this change is increase memory usage per process.  80B is good  compromise between memory usage and log line length.
> stdio: Increase default stream size for NOMMU

- Makefile
provide lpthread symlink 
POSIX compliance
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/c99.html
> provide lpthread symlink (POSIX compliance)

- include/netinet/tcp.h
> include: add TCP_KEEPALIVE and TCP_KEEPCNT defines

- stdlib/strtod.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/607
On zynq7k:
On ia32-generic:
JIRA: RTOS-365
> strtod: Fix handling of negative values

- stdio/scanf.c
JIRA: RTOS-376
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/617
> stdio/scanf: Add 't' conversion

- sys/ioctl.c
Needs also a patch in use-cases (i.e. phoenix-rtos-devices).
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/635
> sys/ioctl: Fix malloc return value not being checked

- stdio/format.c
- Add dummy support for 'L' length modifier (long double is cast to double)
- Add support for 'h' and 'hh' length modifiers
- Add support for 't' length modifier
DONE: RTOS-356
> stdio/format: Add support for hh, h and t length modifiers

- stdio/format.c
> stdio/format: Fix precision modifier for integers

- include/stdio.h
- stdio/file.c
Only the `fgetpos()`, `fsetpos()` function prototypes were available in `libphoenix`, but implementations of the functions were missing. This PR adds implementation of both functions.
There is placeholder for the tests: [phoenix-rtos-tests/libc/stdio_file.c#L689-L696](https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/3ead4a4ed91b28f50e020413ebd2dcf8c0558dde/libc/stdio_file.c#L689-L696) 
Added PR with test https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/175
JIRA: RTOS-392
> stdio: Add `fgetpos()` and `fsetpos()`

- include/unistd.h
- unistd/Makefile
- unistd/pause.c
DONE: RTOS-394
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/646
> unistd: Add pause() implementation

- include/stdlib.h
- stdlib/malloc_dl.c
DONE: RTOS-401
Solves https://github.com/phoenix-rtos/phoenix-rtos-project/issues/660
> malloc: Add malloc_usable_size()

- stdio/bignum.c
- stdio/bignum.h
- stdio/format.c
- stdio/format.h
- stdio/fprintf.c
- stdio/printf.c
- stdio/sprintf.c
1. Fix an issue with `format_parse` failing silently. After this change, it returns an error code.
2. Fix an issue with %f allocating too much memory.
`printf` causes issues on some platforms with no MMU and small amount of memory.
> stdio/printf: Fix some issues with printf

- stdio/scanf.c
This change introduces the followng principle of ungetting characters to the stream: first use `ungetc()`, eg. when used with `stdin`, if it fails in case of buffer limit `BUFSIZ` as fallback continue using `fseek` (negative offset from the current position).
NOTE: on `NOMMU` targets `BUFSIZ` is very small (80 characters) when comparing to `MMU` targets where it's size is set to `_PAGE_SIZE`.
JIRA: RTOS-393
> stdio: fix scanf setting position indicator

- arch/sparcv8leon3/Makefile
- arch/sparcv8leon3/_start.S
- arch/sparcv8leon3/jmp.S
- arch/sparcv8leon3/reboot.c
- arch/sparcv8leon3/signal.S
- arch/sparcv8leon3/string.c
- arch/sparcv8leon3/syscalls.S
- include/arch.h
- include/arch/sparcv8leon3/arch.h
- include/arch/sparcv8leon3/limits.h
- include/arch/sparcv8leon3/stdint.h
- include/arch/sparcv8leon3/types.h
> libphoenix: add sparcv8leon3 target

- arch/sparcv8leon3/_start.S
- arch/sparcv8leon3/jmp.S
- arch/sparcv8leon3/syscalls.S
Implement arch-dependent functions for `sparcv8leon3` target with use of register windows
JIRA: RTOS-406
> Leon3: use register windows

- stdio/file.c
Also add n overflow handling and min size
DONE: RTOS-479
See JIRA RTOS-479 for context.
> getdelim: Fix buffer overflow (c == delim, n == 1 case)

- include/stdio.h
- stdio/file.c
DONE: RTOS-494
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/734
> file: fflush all output streams on fflush(NULL)

- include/dirent.h
- unistd/dir.c
DONE: RTOS-413
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/649
> dirent: Add rewinddir implementation

- sys/time.c
DONE: RTOS-415
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/651
> Add utime implementation

- include/unistd.h
- unistd/sysconf.c
> libphoenix:  lack of _SC_ATEXIT_MAX in sysconf()

- string/string.c
JIRA: RTOS-458
Posix stands that these values should be type casted. Without it some tests were failing.
strcmp: https://pubs.opengroup.org/onlinepubs/009604499/functions/strcmp.html
strchr: https://pubs.opengroup.org/onlinepubs/007904975/functions/strchr.html
> string: fix lack of type casts

- arch/sparcv8leon3/_start.S
- arch/sparcv8leon3/syscalls.S
DONE: JIRA: RTOS-516
Kernel commit SHA: `3cb1ba6`
> sparcv8leon3: adapt assembly code to kernel changes

- arch/sparcv8leon3/reboot.c
> arch/sparcv8leon3: implement cpu reboot

- arch/riscv64/jmp.S
> arch/riscv64: fix setjmp/longjmp

- stdio/file.c
DONE: RTOS-503
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/260
> puts: Return EOF on error

- unistd/sys.c
> Fix execve not setting errno in some cases

- arch/armv7a/jmp.S
- arch/armv7m/jmp.S
DONE: RTOS-600
Fixes https://github.com/phoenix-rtos/libphoenix/issues/175
> armv7a: Use better set/longjmp implementation from armv7m 

- Makefile
- _startc.c
- arch/armv7a/Makefile
- arch/armv7m/Makefile
- arch/ia32/Makefile
- arch/riscv64/Makefile
- arch/sparcv8leon3/Makefile
- crt0.o should call make() (otherwise linking might fail)
- crt0.o should have program entry point + necessary setup (dynamic lib use case)
JIRA: CI-334
> make: introduce real crt0.o

- include/sys/msg.h
> Adapt to msgRecv, msgRespond API change

- stdio/bignum.h
- stdio/format.c
- stdio/format.h
- stdio/fprintf.c
- stdio/scanf.c
Fixes  https://github.com/phoenix-rtos/phoenix-rtos-project/issues/677
> scanf: support (nil) as NULL ptr

- include/dirent.h
> dirent: Remove non-standard dirent types enum

- include/stdlib.h
- stdlib/atexit.c
JIRA: RTOS-636
FIxes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/871
> atexit: allow for calling atexit inside of atexit

- include/pthread.h
- pthread/pthread.c
fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/827
DONE: RTOS-671
> pthread: implement cleanup_push/_pop

- include/ctype.h
DONE: RTOS-673
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/916
> ctype: Fix typo

- include/sys/file.h
> sys/file: Remove dead function prototypes

- stdlib/strtod.c
JIRA: RTOS-751
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/912
> stdlib/strtod: remove duplicate set errno

- arch/ia32/string.c
- include/string.h
JIRA: RTOS-752
Unused function.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/961
> string: remove memsetw

- arch/armv7a/crt0.S
- arch/armv7m/crt0.S
- arch/ia32/crt0.S
- arch/riscv64/crt0.S
- arch/sparcv8leon3/crt0.S
- crt0-common.c
https://github.com/phoenix-rtos/libphoenix/pull/313
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/497
> Add support for cleanup function

- include/sys/socket.h
> socket.h: define MSG_NOSIGNAL

- include/strings.h
- string/string.c
JIRA: RTOS-763
Provide `ffs` function using builtin implementation
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/993
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/768
> strings: add `ffs` function

- arch/riscv64/reboot.c
> riscv64: add system reset handling

- arch/riscv64/reboot.c
> riscv64/reboot: fix include path

- include/errno.h
JIRA: RTOS-778
This pr needs https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/521
> include: remove EMSGSIZE errno

- sys/Makefile
- sys/mman.c
JIRA: RTOS-808
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/977
> sys/mman: Set errno on mmap and munmap

- include/stdio.h
- include/syslog.h
Makes compiler test arguments' types to the format functions at a compile time.
JIRA: RTOS-849
> format: add function format attributes

- arch/sparcv8leon3/reboot.c
> arch/sparcv8leon3: name union in platformctl_t

- include/time.h
- time/time.c
JIRA: RTOS-867
Necessary for cFS port.
> time: implement clock_settime

- include/stdint.h
> stdint: fix definitions of limits of exact-width integer types

- pthread/pthread.c
> pthread_key_create: fix null pointer check

- include/unistd.h
- stdio/file.c
- stdio/fprintf.c
- unistd/Makefile
- unistd/file-internal.h
- unistd/file.c
- unistd/hostid.c
> unistd: implement get/sethostid functions

- unistd/file-internal.h
- unistd/file.c
JIRA: RTOS-882
Fix failing nightly
> unistd/file: fix __safe_read/write return value

- arch/arm/Makefile
- arch/arm/v8r/Makefile
- arch/arm/v8r/reboot.c
- arch/arm/v8r/syscalls.S
- include/arch.h
- include/arch/armv8r/arch.h
- include/arch/armv8r/limits.h
- include/arch/armv8r/setjmp.h
- include/arch/armv8r/stdint.h
- include/arch/setjmp.h
> arch: add ARMv8-R support

- include/locale.h
- locale/locale.c
DONE: RTOS-856
Currently, `struct lconv` has only one standard member, whereas there are many more. This change introduces all of them, modernizes and standardizes function declarations and definitions. ~~Unfortunately, this makes `fixed_locale` non-const, but modification of this struct by the pointer returned from `localeconv()` is prohibited by the standard.~~
> locale: Fix incomplete locale.h

- arch/sparcv8leon3/reboot.c
> arch: add sparcv8leon3-generic target

- include/errno.h
JIRA: RTOS-877
errnos moved to kernel
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/572
> include: remove EALREADY, EINPROGRESS errnos

- signal/signal.c
> feat(signal): implement sigisemptyset and sigfillset

- include/phoenix/fbcon.h
> phoenix: add fbcon ioctls

- arch/sparcv8leon/Makefile
- arch/sparcv8leon/crt0.S
- arch/sparcv8leon/jmp.S
- arch/sparcv8leon/reboot.c
- arch/sparcv8leon/signal.S
- arch/sparcv8leon/string.c
- arch/sparcv8leon/syscalls.S
- arch/sparcv8leon3/Makefile
- include/arch.h
- include/arch/setjmp.h
- include/arch/sparcv8leon/arch.h
- include/arch/sparcv8leon/limits.h
- include/arch/sparcv8leon/setjmp.h
- include/arch/sparcv8leon/stdint.h
JIRA: RTOS-883
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/229
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/520
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/141
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/617
https://github.com/phoenix-rtos/libphoenix/pull/390
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/217
https://github.com/phoenix-rtos/plo/pull/366
> arch: rename sparcv8leon3 to sparcv8leon

- stdio/scanf.c
- Fix SEGFAULT caused by invalid processing of %n
- MISRA
Fixes: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1059
JIRA: RTOS-825
> libphoenx/scanf: Fix SEGFAULT caused by invalid processing of %n

- stdio/file.c
> stdio/file: fix write_buffer()

- stdio/file.c
> stdio/file: make rewind clear error indicator

- signal/signal.c
> signal: improve POSIX compliance

- arch/sparcv8leon/reboot.c
JIRA: RTOS-883
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
> arch/sparcv8leon: add support for GR740 CPU

- include/limits.h
- include/posix/limits.h
> posix: create header with POSIX defined limits

- include/unistd.h
> unistd: define POSIX constants

- include/sys/ioctl.h
KIOEN is used to enable / disable klog printing on given console.
JIRA: RTOS-998
> sys/ioctl: define KIOEN ioctl

- sys/mman.c
> !mman: set errno in mprotect

- math/exp.c
POSIX requirement.
JIRA: RTOS-1023
> modf: always assign to intpart

- sys/stat.c
> creat: change mode type to mode_t

- include/sys/utsname.h
- sys/Makefile
- sys/uname.c
JIRA: RTOS-1017
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/640
> sys/utsname: create and implement uname

- arch/aarch64/signal.S
- arch/arm/signal.S
- arch/ia32/signal.S
- arch/riscv64/signal.S
- arch/sparcv8leon/signal.S
- signal/signal.c
Fixes: phoenix-rtos/phoenix-rtos-project#1234
Fixes: phoenix-rtos/phoenix-rtos-project#1306
PR with tests: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1307
> signal: sigmask and sigsuspend fixes

- pthread/pthread.c
> Cherry pick pthread_cancel deadlock fix to release 3.3

- arch/arm/v8m/reboot.c
> arch: add STM32N6 target

- arch/arm/v7r/reboot.c
> arch: add TDA4VM target

- include/arch/sparcv8leon/stdint.h
> sparcv8leon/stdint: fix 64 bit macros definitions

- signal/signal.c
Resolves phoenix-rtos/phoenix-rtos-project#1367
JIRA: RTOS-1097
> signal: fix sigaction temporary unmasking other signals

- signal/signal.c
JIRA: RTOS-1097
(cherry picked from commit b3daaed1051b9b2cb9937d7e5510e44718afac65)
> signal: fix sigaction temporary unmasking other signals (backport to release/3.3)
